// <auto-generated />
namespace MusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addalbumautor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addalbumautor));
        
        string IMigrationMetadata.Id
        {
            get { return "201709050941142_add-albumautor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
